# Generated by Django 2.1.3 on 2018-11-03 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='companyID',
        ),
        migrations.AddField(
            model_name='companies',
            name='userID',
            field=models.ForeignKey(db_column='userID', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
